version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  mqtt-publisher:
    lang: node12
    handler: ./mqtt-publisher
    image: ${DOCKER_USER:-alexellis2}/mqtt-publisher:0.0.0
    labels:
      com.openfaas.scale.min: 0
      com.openfaas.scale.max: 10
    secrets:
      - emitter

  db-inserter:
    lang: node12
    handler: ./db-inserter
    image: ${DOCKER_USER:-alexellis2}/db-inserter:0.3.7
    annotations:
      topic: "drone-position/,drone-event/"
    environment:
      db_port: 5432
      db_name: postgres
    labels:
      com.openfaas.scale.min: 5
      com.openfaas.scale.max: 10
    secrets:
      - db

  db-reader:
    lang: node12
    handler: ./db-reader
    image: ${DOCKER_USER:-alexellis2}/db-reader:0.3.3
    environment:
      db_port: 5432
      db_name: postgres
    labels:
      com.openfaas.scale.min: 5
      com.openfaas.scale.max: 5
    secrets:
      - db
    
  # Microservice to render static HTML
  render-map:
    lang: dockerfile
    handler: ./render-map
    image: ${DOCKER_USER:-alexellis2}/render-map:0.3.4
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1
